import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./fontawesome";
import NavBar from "./Components/NavBar/NavBar";
import ResponsiveNavBar from "./Components/NavBar/ResponsiveNavBar";
import { Footer } from "./Components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          <ResponsiveNavBar />
          <div className=" h-[102px] lg:h-[134px] bg-offWhite"></div>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
